apiVersion: v1
kind: Secret
metadata:
  name: prosync-secrets
  namespace: default
type: Opaque
data:
  # Example: base64 encoded secrets
  POSTGRES_URL: <BASE64_ENCODED_URL>
  MONGODB_URL: <BASE64_ENCODED_URL>
  REDIS_URL: <BASE64_ENCODED_URL>
